### ISSUE TITLE
split up feed

### ISSUE THREAD

**Issue by Bubu** [mvdan/gibot#10]
Would it be possible to split the feed messages between #fdroid and #fdroid-dev? 

We'd like to have at least all push events and possibly also MR events in #fdroid-dev but keep the issues opened and new forum posts in #fdroid.

**Comment by mvdan** [comment]
Sure, it would be possible. The config and code would need to be made a bit more complex.

But I thought someone was replacing gibot with something else. I'd rather not spend an afternoon improving the software if it's going to be replaced soon.

**Comment by mvdan** [comment]
I don't plan to work on this myself, so I'm closing this issue for now.
