### ISSUE TITLE
GitHub webhook support

### ISSUE THREAD

**Issue by stapelberg** [mvdan/gibot#11]
Would a PR be accepted to implement GitHub webhooks? As GitHub is turning down GitHub Services, I’m looking for a replacement solution :)

**Comment by mvdan** [comment]
Sure. Do note that this was mostly written in the summer of 2015, back when I had much less experience in Go and in coding in general. There's zero tests and the code is a bit atrocious :)

Otherwise it still works - F-Droid still uses it today. Happy to review and accept patches.

**Comment by stapelberg** [comment]
Yeah, I have code like that myself from when I was in the same situation :)

Sent PR #12.
